exclude: ".venv/,build/,dist/,htmlcov/,venv/,.coverage,.env,coverage.xml"
default_install_hook_types:
  - commit-msg
  - pre-commit
repos:

  ##### Formatters #####

  - repo: https://github.com/omnilib/ufmt
    rev: v2.2.0
    hooks:
      - id: ufmt
        additional_dependencies:
          - black == 23.7.0
          - usort == 1.0.7
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: pretty-format-json
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter

  ##### Linters #####

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: ["--unsafe"]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-no-eval
      - id: python-use-type-annotations
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.287
    hooks:
      - id: ruff
        args: ["--fix", "--line-length=120", "--ignore=E711"]
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        args: ["--ignore", "B6", "-c", "title-max-length.line-length=120", "--msg-filename"]
