[tool.poetry]
name = "protokol"
version = "1.3.3"
description = "NATS-oriented RPC and Event protocol"
authors = ["Sergey Zhegunya <harmonicsseven@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7"
nats-py = "^2.2.0"
loguru = "^0.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
